// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjdBccXSTDEmoEVUaQfwIwU4y_zCqkTz8',
    appId: '1:261289819691:web:7331a0c646e16668fdf46e',
    messagingSenderId: '261289819691',
    projectId: 'sago-app',
    authDomain: 'sago-app-f614b.firebaseapp.com',
    storageBucket: 'sago-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIkqF2vUTi9RLWG41wYonfdmvajsAG1-Q',
    appId: '1:261289819691:android:6aba7ce4d9c5aacdfdf46e',
    messagingSenderId: '261289819691',
    projectId: 'sago-app',
    storageBucket: 'sago-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCndGV47pHhzZ1R-zHGmsRX0oGeylrkdM4',
    appId: '1:261289819691:ios:178ea866efec9519fdf46e',
    messagingSenderId: '261289819691',
    projectId: 'sago-app',
    storageBucket: 'sago-app.appspot.com',
    iosClientId: '261289819691-3pt6l7rcqncsh7upv3f6e62fj9ilcdg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.sagoUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCndGV47pHhzZ1R-zHGmsRX0oGeylrkdM4',
    appId: '1:261289819691:ios:178ea866efec9519fdf46e',
    messagingSenderId: '261289819691',
    projectId: 'sago-app',
    storageBucket: 'sago-app.appspot.com',
    iosClientId: '261289819691-3pt6l7rcqncsh7upv3f6e62fj9ilcdg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.sagoUser',
  );
}
